spring:
  servlet:
    multipart:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/recruiting
    username: recruiting
    password: recruiting

logging:
  level:
    org:
      hibernate:
        type: trace

openai:
  api:
    url: https://api.openai.com/v1/chat/completions
    key: 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